language: python
python:
  - "2.7"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover -s tests -p *_test.py; fi
notifications:
  email: 
    - travisci@sublim.nl

